micronaut:
  application:
    name: keyManagerREST

grpc:
  client:
    plaintext: true
    max-retry-attempts: 5
  channels:
    pix:
      address: ${APPLICATION_HOST:http://localhost:50051}
      plaintext: true
      max-retry-attempts: 5